title: Rahul's Blog
author: rkochhar11
email: rkochhar@ebnet,org
description: > # this means to ignore newlines until "baseurl:"
  This is the description for a blog about programming and random things.

# social links
instagram_username: rahul_kochhar  # DO NOT include the @ character, or else the build will fail!
github_username:  rkochhar11 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: jekyll-podcaster
